.github/workflows/new-issues-to-icebox.yml
This github action will create a new card for every issue opened, and
add it to the "Icebox" column of the "operations-engineering" project.
More information about this github action can be found here:
https://github.com/alex-page/github-project-automation-plus
fixes #45
=> Add github action to add new issues to Icebox

.github/workflows/new-issues-to-icebox.yml
This action was failing with 
```
Resource not accessible by integration
```
I think this relates to [this issue](https://github.com/alex-page/github-project-automation-plus/issues/51) so I'm replacing the default, automatically-provided `GITHUB_TOKEN` secret with a personal access token (PAC) belonging to the `cloud-platform-moj github bot account (which I have added to the `operations-engineering` github team).
This token has `repo` scope, and has been enabled for MoJ SSO, and added to this repo as the secret `CLOUD_PLATFORM_MOJ_GITHUB_TOKEN`
I'm hoping this will enable this action to work as it's supposed to.
=> Use bot user PAT for issue automation

source/documentation/index.html.md.erb
Although the `current_page.data.title` works fine in preview mode, it
causes errors when the site is published.
This change should fix that, and allow the publishing process to
succeed.
related to #37
=> Use hard-coded page title to fix publish process

source/documentation/adrs.html.md.erb, source/documentation/adrs/adr-000.html.md.erb, source/documentation/index.html.md.erb, source/documentation/runbooks.html.md.erb, source/documentation/runbooks/add-a-runbook.html.md.erb, source/documentation/services.html.md.erb, source/index.html.md.erb
* Add pages for ADRs, Services, Runbooks
* Add first runbook & ADR
* Rearrange Services content
You can see a copy of this site with these changes
merged [here](https://digitalronin.github.io/operations-engineering/#moj-operations-engineering)
=> Add initial structure and content

source/documentation/services.html.md.erb
The repo has been renamed from `operations-engineering-github-collaborators` to `github-collaborators`
=> Update github collaborators link

source/documentation/services.html.md.erb
Replacing link for LastPass.com with a link to Ministry of Justice security guidance and process
=> Replace LastPass link

source/documentation/services.html.md.erb
We no longer just offer Places API keys. Name changed to reflect new OS service
=> Rename OS API link

.github/workflows/check-links.yml, .github/workflows/publish.yml
This include ignoring 403 and 0 response error code in htmlproofer link checks
=> Bump tech-docs-publisher image version to 1.4.

source/documentation/services.html.md.erb
To help people trying to look for a solution -- it might not be a good place _here_, though
Context: I thought about this because for APM, HMPPS uses Azure AppInsights and I was wondering if alternatives can be suggested here later on
----
This change renders like this:
=> Add use cases for all services

source/documentation/runbooks/manual-ssl-certificate-processes.html.md.erb
Domains of the format *.cjscp.org.uk are also owned by HMCTS so do not require renewal by Operations Engineering
=> Add *.cjscp.org.uk domain exceptions

source/documentation/services.html.md.erb
Remove link to Heroku as service is no longer used/supported.
=> Remove link to Heroku

config/tech-docs.yml
We shouldn't be using these on this site as it's not part of GOV.UK:
https://www.gov.uk/service-manual/design/making-your-service-look-like-govuk#if-your-service-isnt-on-govuk
We also shouldn't be using the New Transport font, but it's harder to change
that as the govuk_tech_docs gem doesn't have a setting for it:
https://github.com/alphagov/tech-docs-gem/issues/138
=> Stop using the GOV.UK logo and crown in the header

.github/workflows/move-dependabot-issues.yml
Overview
---
This PR connects to https://github.com/ministryofjustice/operations-engineering/issues/2153 and https://github.com/ministryofjustice/operations-engineering/pull/2288 which creates a way for operations-engineering to automate moving tickets dependant on their label. In this instance all we have to do is run the script and allow the default values to do the rest.
What does this PR do
---
By adding this github action, any dependabot PRs will be moved the 'Refined and Ready' "pipeline" in Zenhub. Initially, this should be on manual trigger, but will eventually lead to cron driven.
=> Add github action to move dependabot tickets to Refined and Ready

.github/workflows/format-code.yml
If a PR is in draft i.e. a work in progress, we don't want a commit to tell us the code is incorrectly formatted. When moved to 'Ready for Review', the check should then trigger and perform the necessary changes.
=> Don't trigger formatter on draft PRs

python/scripts/assign_support_tickets.py, python/services/github_service.py, python/test/test_assign_support_tickets.py, python/test/test_github_service.py
Overview
---
This PR refactors the auto-assignment script and adds almost full test coverage. It leverages the new GitHub service layer and creates additional business logic to:
- grab all open issues in the repository passed to it.
- identify the issues labelled with the tag passed to it.
- assign the issue to the user who raised the issue.
There is no additional functionality here, only the ability to change the script and supporting service layer.
=> Refactor support assignment script

.github/workflows/move-dependabot-issues.yml
This commit changes when the dependabot issues lookup occurs. All dependabot checks for operations-engineering repositories should complete by 0915, which means this action only needs to run once per day at 0915.
=> refactor(dependabot): change schedule to run at 0915

source/documentation/services/SSL-certificate-management.html.md.erb
This document is a user facing guide. It duplicates a bunch of steps that are internal to the Ops Eng Team that users don't need to know about. This removes duplication in other documents and makes user docs easier to understand.
=> Remove Ops Eng Process Steps

.github/workflows/check-links.yml, .lycheeignore
This PR closes https://github.com/ministryofjustice/operations-engineering/issues/2578 by adding arguments to lychee to exclude URLs we can't or don't worry about.
=> Add accepted http codes and ignores to lychee

source/documentation/services.html.md.erb
Replace LastPass reference with 1Password. There is no documentation link as guidance is still under review with Security. Will be replaced when available.
=> Replace LastPass reference with 1Password

.github/workflows/check-links.yml
At 0400 we clash with the github standards report work, which coincidently fails this check.
=> Change link check time to 0205

.github/workflows/publish.yml
I've noticed this pipeline always triggers every commit to this repo. It's a waste of compute in most cases and should only trigger when the documentation changes.
=> Don't always publish the ops eng documentation

source/documentation/runbooks.html.md.erb, source/documentation/runbooks/services/1password-chrome-extension-conflict.html.md.erb
1Password Chrome Extension and Google Docs use the same keyboard shortcut for different things which stops the user editing a document. This is a runbook to help the user fix this issue.
=> And runbook to address shortcut conflicts

python/scripts/report_on_repository_standards.py, python/services/operations_engineering_reports.py, python/services/standards_service.py, python/test/test_operations_engineering_report.py
Overview
---
It was decided that we no longer require data encrypted before we send it to the Operations Engineering Reports API. This was previously a non-functional requirement that's no longer needed, so this PR removes the method and all calls made before POST'ing to the API.
=> Remove Encryption from GitHub Repository Reports

python/requirements.txt, python/services/notify_service.py, python/test/test_config.py, python/test/test_notify_service.py
This is the Notify service taken from the [operations-engineering-certificate-renewal](https://github.com/ministryofjustice/operations-engineering-certificate-renewal) repo. 
The code for review are the additional functions and classes added to the files:
send_email_reply_to_ops_eng()
class TestSendEmailReplyToOpsEng
class TestGetNotificationsByTypeAndStatus
=> Add the Notify service and unit tests

python/scripts/report_on_repository_standards.py, python/services/operations_engineering_reports.py, python/services/standards_service.py, python/test/test_standards_service.py
This PR fixes two issues with the operations-engineering github standards reports.
1. It increases the timeout when sending reports to the API.
2. It fixes a condition where a default branch name doesn't exist.
=> 🐛 Fix timeouts and branch failures on reports 

python/requirements.txt
PyJWT is imported by packages within the ops-eng repo ie PyGithub imports PyJWT. By adding jwt to the requirements file it will install https://github.com/GehirnInc/python-jwt. The jwt package can cause a conflict at runtime. This ensure PyJWT is installed, allows moj_git_auth.py to import jwt and ensure the NotificationsAPIClient package uses PyJWT as well
=> Use PyJWT over jwt in requirements.txt

.github/workflows/generate-github-standards-report.yaml, python/scripts/report_on_repository_standards.py, python/services/github_service.py, python/services/operations_engineering_reports.py
This PR connects to https://github.com/ministryofjustice/operations-engineering/issues/2243 and prepares the GitHub Standards Reports for a GitHub Action and public logging. 
- It removes the verbose logging from the graphql query.
- It creates an action to execute the Python script `report_on_repository_standards.py`.
- It removes some unwanted comments from the code base.
- After identifying an issue sending large chunks of reports to the reports API service, the dynamo db instance in the cloud platform cannot handle the write capacity. This is mitigated by chunking up the list of reports and sending them in batches of 100.
=> Create a GitHub Action for report creation

.github/workflows/generate-github-standards-report.yaml
To ensure this works as intended, this commit removes the noise when the action fails, it also adds the required parameters to make the script run.
=> 🚧 Remove slack message on failure; amend params

source/documentation/services/github-feature-request.html.md.erb, source/documentation/services/moj-github.html.md.erb
Updated the GitHub Enterprise Management README to include a link to the newly created Feature Request Guide. This guide provides detailed instructions for developers and analysts on how to submit feature requests and track their progress. This new guide and updated link aim to facilitate better communication between the operations engineering team and developers or analysts seeking enhancements to GitHub. Also, improved the content of some sections for better understanding and clarity.
=> 📝 Add GitHub Feature Request Information

source/documentation/runbooks.html.md.erb, source/documentation/runbooks/services/handling-github-feature-requests.html.md.erb, source/documentation/services/github-feature-request.html.md.erb, source/documentation/services/moj-github.html.md.erb
This PR connects to https://github.com/ministryofjustice/operations-engineering/issues/3147/
Added a detailed runbook outlining the process by which the Operations Engineering team handles third-party feature requests to GitHub. 
The runbook details the monthly review process with GitHub's Technical Account Manager, the usage of the GitHub Project Board for tracking request statuses, and the communication process post-meeting. 
This will ensure a transparent, structured process for all involved parties.
=> 📝 Add Runbook for Handling Third-Party GitHub Requests

python/services/operations_engineering_reports.py, python/test/test_operations_engineering_report.py
This commit adds retry logic to the `__http_post` method in the `ReportsService` class. The `Retry` object from the `requests` library is used to automatically retry failed requests up to 3 times, with a backoff factor of 1 second between retries.
The `status_forcelist` parameter is set to `[500, 502, 503, 504]` to retry requests that fail due to server errors. The `method_whitelist` parameter is set to `["POST"]` to retry only POST requests. This improves the reliability of the `ReportsService` class when making HTTP POST requests to the API.
=> ⚡️  Add retry logic to HTTP POST requests

source/documentation/runbooks.html.md.erb, source/documentation/runbooks/services/managing-github-notifications.html.md.erb, source/documentation/services/moj-github.html.md.erb
This PR connects to https://github.com/ministryofjustice/operations-engineering/issues/3143 and introduces a new section in our GitHub Enterprise Management documentation. 
The section links to a comprehensive guide on managing GitHub notifications effectively. The aim is to help our developers and teams control their notification settings to reduce noise and focus on important updates. This should improve productivity and enhance the overall GitHub experience within our organisation.
=> 📝  Add GitHub Notifications Management Guide

source/documentation/runbooks/internal/respond-to-leavers.html.md.erb
As LastPass has been decommissioned we won't need to remove LastPass accounts when a user leave the MoJ.
=> Remove reference to LastPass

source/documentation/runbooks/services/self-managed-github-teams.html.md.erb
This PR connects to https://github.com/ministryofjustice/operations-engineering/issues/3149 and details instructions on how to opt into a GitHub teams activity monitor feature.
=> 📝 Add a user-guide entry for self-managed github teams

.github/workflows/report-unowned-repository.yaml
This action triggers the unowned_repositories python script from the
repository at 0600 every morning. This PR makes the following
assumptions:
- The `unowned_repositories.py` exists and is exectuted in the same
manor.
- The script will only run once per day.
- The script will perform the post to slack call, not the action.
=> :construction_worker: Add GH Action to report on unowned repositories

python/scripts/report_on_repository_standards.py, python/services/github_service.py, python/services/operations_engineering_reports.py, python/test/test_operations_engineering_report.py
Overview
---
This PR addresses the lack of logging in the operations-engineering-reports service class and attempts to improve the visibility of failing POST calls to the API. By merging this PR into the service, we will have a better idea as to why the GitHub Action is falling and perhaps offer a more concrete solution.
Examples of failing workflows:
https://github.com/ministryofjustice/operations-engineering/actions/runs/6375823736
=> Improve logging and add log level argument

python/services/operations_engineering_reports.py
Fixes the error [seen in the CI](https://github.com/ministryofjustice/operations-engineering/actions/runs/6477815363/job/17588607600):
```TypeError: Retry.__init__() got an unexpected keyword argument 'method_whitelist'```
`method_whitelist` was deprecated from urllib3==1.26.0 and removed in urllib3==2.0.0 (released April 2023) - see: https://github.com/urllib3/urllib3/blob/main/CHANGES.rst#200-2023-04-26
urllib3 is one of the dependencies of 'responses' - it just asks for the latest 2.x.x version: https://github.com/psf/requests/blob/main/setup.py#L64 I'm not sure why this didn't shown up in April 🤷
=> Fix reports for newer urllib3 syntax of "method_whitelist"

bin/alert_on_low_github_licences.py, requirements.txt, services/github_service.py, test/test_github_service.py, test/test_low_github_licences.py
Overview
---
This PR connects to https://github.com/ministryofjustice/operations-engineering/issues/3764 and is related to the requirement to alert when we fall below a certain number of GitHub licences/seats.
=> 🔔 Create a triggered alarm for low GitHub licences (Under 10)

services/github_service.py, test/test_github_service.py
- To fix a bug with the current implementation that was raised in https://github.com/ministryofjustice/operations-engineering/issues/3904 - where required status checks are removed for repositories that have the topic of `standards-compliant`
- Added logic to retrieve the current required checks, and pass them through when we make the call to edit the protection rules
- It should be noted that we may be modifying other fields as well, for example, if "number of approvers" is set to 2, we will amend this to 1. Our documentation is not clear about this. This process is potentially misconfiguring repositories where the team has set custom branch protection values.
=> 🔧 Fix Set Standards not retaining existing required status checks

services/github_service.py, test/test_github_service.py
- To fix the scenario where a repository does not have required checks and provide some default blank values
- added default values for when the required checks object is being read
- Fixes issue caused in https://github.com/ministryofjustice/operations-engineering/pull/3909
- Initial attempt was in https://github.com/ministryofjustice/operations-engineering/pull/3911
=> 🔧 Fix error when `required_status_checks` don't exist (attempt 2 with tests 🧪)

.github/workflows/archive-repos.yml, .github/workflows/mojas-archive-repos.yml
Now that repo archiving workflows is fixed ([#3905](https://github.com/ministryofjustice/operations-engineering/issues/3905)) reinstate the workflows to their original schedule. 𐅐
=> Reinstate archive repo workflow schedule

.github/workflows/check-for-new-github-owners.yml, bin/check_for_github_admins.py, services/github_service.py, test/test_github_service.py
This PR connects to https://github.com/ministryofjustice/operations-engineering/issues/3760 and creates a weekly alarm that will inform the #operations-engineering slack channel of new GitHub "Owners".
=> :construction_worker: Add GitHub Action to trigger new owners check

bin/sentry_usage_alert.py
- To lower the noise of these alerts (especially over the Christmas period), as high usage teams are struggling to deploy their changes to lower their sampling rates
- Increased threshold form 60% to 80%
- We should start investigating if any more teams in the top 10 or 20 may be able to reduce their usage faster
- 80% is probably as high as we want to go with the threshold, we should look at increasing the quota/being stricter with teams if we need to go any higher
=> 👆 Bump Sentry Usage Alert Threshold

.pylintrc
- In relation to https://github.com/ministryofjustice/operations-engineering/issues/3953
- To ignore doc string recommendations, most of our code doesn't have them and we shouldn't be trying to enforce it - as code should mainly be self-describing
- Also ignored the `line-to-long`, we can probably re-introduce this later after we've tidy up more important issues
- Added `missing-module-docstring`. `missing-function-docstring`,`line-too-long` to the .pylintrc
=> ✨ Add `missing-module-docstring`. `missing-function-docstring`,`line-too-long`

.pylintrc, bin/alert_on_low_github_licences.py, bin/check_for_new_github_owners.py, bin/configure_standards.py, bin/mass_permission_update.py, bin/remove_collaborator_locked_repos.py, bin/report_on_repository_standards.py, bin/unowned_repositories.py, config/constants.py, services/metadata_service.py, services/slack_service.py, test/test_bin/test_low_github_licences.py, test/test_bin/test_report_on_inactive_users.py, test/test_bin/test_unowned_repositories.py, test/test_services/test_metadata_service.py, test/test_services/test_operations_engineering_report.py, test/test_services/test_s3_service.py
- In relation to https://github.com/ministryofjustice/operations-engineering/issues/3953
- To align our codebase with some of our linting rules
- Re-arranged and tidied up some imports
- Using `is` instead of `==` where it's safe and recommended
- Added timeouts to HTTP calls
- Added missing-class-docstring to ignore list in pylint
- Moved some constants into the constants file
- ...and a few other bits that I won't detail here
- There are still a fair few errors, and will need to fix these (or ignore them) as we work through the code
- I stayed away from the GitHubService class, as it's a bit of beast - will probably need it's own PR
=> 🔧 Fix some linting issues

terraform/github/repositories/data.tf, terraform/github/repositories/test-tamf-repo-2.tf, terraform/github/repositories/test-tamf-repo-test-org.tf
- Testing `team_access` input works for team in both `ministryofjustice` and `ministryofjustice-test` orgs.
- `test-tamf-repo-2` to be created in `ministryofjustice` org with `operations-engineering` team associated as maintainers.
- `test-tamf-repo-test-org` to be created in `ministryofjustice-test` org with `operations-engineering-test` team associated as maintainers.
-
=> Test module team_access input

.github/ISSUE_TEMPLATE/trivy-vulnerability-template.md, .github/workflows/cicd-trivy-dependency-scan.yml
This change aims to automatically create issues on the operations-engeering GitHub repository once a trivy scan has been conducted and vulnerabilities have been found.
- Automatic Trivy scans every Monday at 9:00am
- Automatic creation of an issue on the repository detailing why it needs fixing with a link to the security tab.
- Automatic notifications to the operations-engineering-alerts channel to make the team aware a new vulnerability has been found.
No notes to speak of.
=> Automatic Trivy Vulnerability Scanning and Notifications

.github/workflows/job-alarm-for-github-actions-quota.yml, bin/alert_on_low_github_actions_quota.py, services/github_service.py, test/test_bin/test_alert_on_low_github_actions_quota.py, test/test_services/test_github_service.py
**Alerting system for github actions minutes quota usage**
**Github Service**
- get_all_organisations_in_enterprise
- get_gha_minutes_used_for_organisation 
- get_gha_minutes_quota_threshold
- modify_gha_minutes_quota_threshold
*** these pretty much do what their names suggest, subprocess was used in place of PyGithub where the correct functionality was not found in PyGithub. ***
**alert_on_low_github_actions_quota** job in **bin**
- Configure tokens
- Configure services
- Get all orgs in the enterprise
- Get all minutes used by all orgs in enterprise
- Calculate percentage of minutes used
- Reset alerting threshold if first day of month
- Retrieve alerting threshold from Github Actions Variable
- Compare % minutes used to threshold 
- Trigger Slack alert and increment threshold if …
=> Github Actions Quota Usage

services/s3_service.py, test/test_services/test_s3_service.py
R53 backup is uploaded to a new object location in the S3 bucket each time, with the backup date in the name of the object location.
=> Upload each time to new object location

services/github_service.py, test/test_services/test_github_service.py
Adds function to Github Service which takes a list of organisations as an argument and returns a list of all users in all specified organisations.
=> Get users from multiple organisations

services/github_service.py, test/test_services/test_github_service.py
- To automatically remove repositories that have been inactive and contain no commits
- ☝️ This process is currently "manual"
- Removed the logic that kept repositories with no commits around and logged them as "To manually check"
- Refactored logic to automatically remove repositories that are:
- Created more than a year and a half ago
- Have no commits
- Renamed a few tests
- This change removes all manual aspects of the process
- For context, the logic (in priority order) to identify an archivable repository is `Created over a year and a half ago AND is not in allow list AND (has no commits OR latest commit is over a year and half ago)`
---
=> ✨ Add auto removal of inactive repositories with no commits

bin/identify_dormant_github_users.py, test/test_bin/test_identify_dormant_github_users.py
Previously, the `get_usernames_from_csv_ignoring_bots` function returned a list of usernames from a CSV file that weren't identified as bot accounts. This commit makes two significant changes:
1) The function now also excludes outside collaborators. It has been renamed to `get_usernames_from_csv_ignoring_bots_and_collaborators` to reflect this change.
2) The parsing of CSV data has been updated from using a standard reader to a Dictionary Reader for improved readability. Now, instead of indexing column values by their order in the row, they can be accessed via their column header names.
Unit tests have also been updated and expanded to verify these changes.
=> :recycle: Exclude collaborators when identifying dormant users

bin/identify_dormant_github_users.py
This pull request adds a Slack service to the identify_dormant_github_users script. The Slack service allows for notifying dormant GitHub users by sending a message to a specified Slack channel with the list of identified dormant users from GitHub. This improves communication effectiveness and enhances the functionality of the script.
=> Add Slack service to identify_dormant_github_users script

.github/workflows/exprimental-identify-dormant-github-users.yml
This update adds `write` permissions for both `id-token` and `contents` in the GitHub Actions workflow file `exprimental-identify-dormant-github-users.yml`. With this change, the job `identify_dormant_github_users` now has write access that may be necessary for its tasks. Please review and ensure this aligns with our access control policies.
=> :lock: Add write permissions to GitHub Action workflow

.github/workflows/exprimental-identify-dormant-github-users.yml
This secret should be all that's required to access audit log data to confirm dormant github users.
=> :recycle: Update GH_ADMIN_TOKEN secret in dormant-github-users pipeline

.github/workflows/job-apply-standards.yml, bin/configure_standards.py, services/kpi_service.py
- In relation to [#4420](https://github.com/ministryofjustice/operations-engineering/issues/4420)
- To track low risk, simple live metric to prove the concept of a KPI Dashboard
- Added a KPIService for easily allowing scripts to track metrics
- Added a metric tracker to the configure standards job
- Wrapped all additional tracking code in a try/except block - so any errors won't affect normal processing
---
=> ✨ Add KPI tracking for number of repositories with `configure-standards` label

.pylintrc, bin/dormant_users.py
• PR adds `HmppsDigitalServiceAccount` to the dormant users allow list. This account is expected to be low activity which could make the account look dormant and removal of the user could break critical services.
• User `hmppsdigitalserviceaccount` added to allow list
• Update `overgeneral-exceptions` value to fix linting failure
=> Add HmppsDigitalServiceAccount to dormant users allow list

bin/identify_dormant_github_users.py
As this bin file is most likely to be run inside a GitHub Action it needs to exit with non-0. The best way to do this is to let the exception bubble up to the runner and exit forcefully.
=> :recycle: Ensure identify_dormant_github_users fails with exception

terraform/github/repositories/ministryofjustice/operations-engineering-dns-issues.tf
As it's an odd requirement for a GitHub repository, we should be descriptive about its purpose.
=> :recycle: Use precise language in the repository description

terraform/github/repositories/ministryofjustice/operations-engineering-octodns-poc.tf, terraform/github/repositories/ministryofjustice/operations-engineering-terraform-dns-poc
This repository will house code and configuration to prove Terraform is or isn't appropriate to manage our dns estate
=> :sparkles: Add operations-engineering-terraform-dns-poc repository

terraform/dsd/iam/octodns_dns_write.tf
This PR connects to https://github.com/ministryofjustice/operations-engineering/issues/4565
This will create a new user for managing credentials until the route53 provider in OctoDNS gives us the ability to use RBAC. Access and Secret keys are stored in the dns repository.
=> :sparkles: Add IAM user and policy for OctoDNS

services/circleci_service.py, test/test_services/test_circleci_service.py
This change aims to fix inaccurate unused context being reported, by focusing only on the main branch of a repository.
To improve the accuracy of the list of unused contexts that is being generated.
Small URL change to only gather pipelines from the main branch of a project.
No notes.
---
=> :recycle: Exclusively Using the Main Branch for Pipeline Checks

.github/CODEOWNERS
- Added Andy as sole owner of /data/ directory
- Enables daily support stats to be merged without additional approval
- Streamlines process for updating routine operational data
- Only affects /data/ directory; other repo protections remain intact
=> Update CODEOWNERS to allow direct merges for support stats

.github/CODEOWNERS, .github/workflows/cicd-terraform-github-teams.yml, .github/workflows/experiment-auto-approve-support.yml, terraform/github/teams/main.tf, terraform/github/teams/operations_engineering_support.tf, terraform/github/teams/variables.tf
- This PR creates a new Operations Engineering team called `operations-engineering-support`.
- When a member of the new team PRs a change to the `data` directory, they won't need approval from the `operations-engineering` team.
- Implementation of a new Terraform-managed pipeline that creates and manages GitHub teams. This setup:
- Creates a new team called `operations-engineering-support`.
- May evolve to include declaring members of the `operations-engineering` team.
- A change to the CODEOWNERS file, assigning ownership of the `data` directory to the new team.
- A new GitHub Actions workflow to auto-approve PRs from the support team.
- The auto-approve GitHub Action is designed to auto-merge PRs only when they exclusively affect the `data/` directory. If the PR includes changes to …
=> 🔧 Create Operations Engineering Support Team + Auto-approve Support Stats PRs

terraform/dsd/iam/cloud_platform_route53_read_role.tf
- To enable Cloud Platform to create a role to be assumed by this role 🎩 
- Added the `assume_cloud_platform_route53_read_role` 
- The role has no policies at the moment, this will generate an ARN so Cloud Platform can construct a policy to allow this role to assume their Route53 Read Role. Once their role has been created in the Cloud Platform account, we will update the policy for this role to be able to assume their role <insert confused math lady meme / crazyblob slack emoji>
---
=> ✨ Add Role to Assume Cloud Platform Route53 Read Role

terraform/auth0/operations-engineering-test/auth0_import.tf, terraform/auth0/operations-engineering-test/clients.tf, terraform/auth0/operations-engineering-test/tenant.tf
This commit creates infrastructure as code for all items we want to manage in Terraform. I used the auto-generation technique outlined here and hope that after importing, I can remove the auth0_import.tf file.
=> :sparkles: Autogenerate operations-engineering-test terraform configuration

.github/workflows/cicd-terraform-github-repos.yml, terraform/github/repositories/main.tf, terraform/github/repositories/ministryofjustice/operations-engineering-test-secrets-manager.tf
To associate an already existing secret in the AWS Secret Manager (DSD account) to the operations-engineering-test-secrets-manager repository.
- New secret EXAMPLE_SECRET manually added to the AWS Secrets Manager in the DSD account
- EXAMPLE_SECRET defined and added to the operations-engineering-test-secrets-manager repository.
- New role exported to a profile in the workflow, and included in the AWS provider configuration.
•
---
=> Add New Repository Secret to operations-engineering-test-secrets-manager

bin/identify_dormant_github_users.py, services/cloudtrail_service.py, services/github_service.py, test/test_bin/test_identify_dormant_github_users.py, test/test_services/test_cloudtrail_service.py, test/test_services/test_github_service.py
- Adds cloudtrail service to query data lake
- Adds function to retrieve all members of enterprise to github service
- Adds functions to identify dormant users job to compute inactive users from data lake source. These functions replace the old ones which use manually generated csv as a source.
- Unit tests.
=> Automate dormant GitHub users

terraform/github/repositories/main.tf, terraform/github/repositories/variables.tf
To resolve the missing organisation parameter when retrieving the public key or the operations-engineering-test-secrets-manager repository.
- "ministryofjustice" org captured as a variable and referenced in the provider configuration.
Based from [this](https://github.com/integrations/terraform-provider-github/issues/578) discussion.
---
=> Convert owner Value to a Variable

.github/workflows/experiment-cloud-platform-route53-read.yml
- In relation to https://github.com/ministryofjustice/operations-engineering/issues/4523
- In relation to https://github.com/ministryofjustice/cloud-platform/issues/5727#issuecomment-2174133535
- To test authentication to Cloud Platforms Route53 (read-only access)
- Added new workflow which assumes the OE role to assume the CP role and tests authentication by trying to list the hosted zones 
- Added `CLOUD_PLATFORM_ROUTE53_READ_ROLE_ARN` secret to this repository
- Ideally, we want to build this access into some service, product or part of change process, but going to draft up a separate ticket to get that in place
- Can see that this integrated correctly in this run of the action 👉 https://github.com/ministryofjustice/operations-engineering/actions/runs/9939205430/job/27453297647#step:5:1 …
=> 🧪 Test Authentication to Cloud Platform Route53

.github/workflows/cicd-terraform-github-repos.yml, terraform/github/repositories/ministryofjustice/test-tamf-repo-2.tf
To prove that it's possible to add GitHub secrets through Terraform, and reference the value in AWS Secrets Manager.
- Secrets values are now passed through and created by the module. 
- An example of this is in the test-tamf-repo-2 using the one EXAMPLE_SECRET from AWS.
•
---
=> GitHub Secret Injection Through Module

terraform/dsd/iam/dsd_route53_read_role.tf
- In relation to https://github.com/ministryofjustice/operations-engineering/issues/4653
- To enable read only access to the DSD accounts Route53
- Added a new role for Read access to Route53 which can be assumed by this repository
- NA
---
=> ✨ Add DSD Route53 Read Role

.github/workflows/experiment-dns-delegations-metrics.yml
- In relation to https://github.com/ministryofjustice/operations-engineering/issues/4653
- To add a basic workflow which shows that multiple profiles can be used to retrieve DNS information across multiple accounts (DSD and Cloud Platform)
- Added the `DNS Delegations Metrics` Workflow
- This isn't the final script, just the initial setup of the workflow to ensure we can get the right credentials set up. The next iterations will convert the basic bash script into a more comprehensive Python script to gather the metrics 📊
---
=> ✨ Add DNS Delegation Metrics Workflow

.github/workflows/experiment-dns-delegations-metrics.yml, bin/dns_delegations_metrics.py, services/route53_service.py, test/test_bin/test_dns_delegations_metrics.py
- In relation to https://github.com/ministryofjustice/operations-engineering/issues/4653
- To enable automated metric gathering of DNS Delegations
- Added a script to gather metrics about DNS Delegations
- I realise that most Route53 functionality has been migrated to the [https://github.com/ministryofjustice/dns](https://github.com/ministryofjustice/dns) repository - although with this being experimental (and potentially going to make use of the KPI Service) - I thought it best not to add a bunch of experimental code to the DNS repository
---
=> ✨ Add Script For DNS Delegation Metrics

terraform/auth0/operations-engineering/clients.tf
• Remove `encryption-key` which cannot be empty for apply to create
•  deleted `encryption-key = {}` 
• [See here for another instance](https://github.com/auth0/terraform-provider-auth0/issues/909)
• `encryption-key = {}` exists in the other resources as these were generated from existing resources, they have never been created in an apply by `terraform`. However, for a creation apply `encryption-key` cannot be empty.
wrt FIREBREAK: 🔥 Get KPI Dashboard Production Ready [#4612](https://github.com/ministryofjustice/operations-engineering/issues/4612)
---
=> Remove encryption-key which cannot be empty for apply to create

config/constants.py
Sean is taking over as head of hosting, so will be getting access to various things. We don't want to alert about his presence, so this adds him to the list of people who should have access.
This also removes Vijay, who left us a short while back.
- 🚫 ~I have run all unit tests, and they pass~
- 🚫 ~I have ensured my code follows the project's coding standards~
- 🚫 ~I have checked that all new dependencies are up to date and necessary~
I have done none of these things, sorry!
=> Ensure new head of hosting doesn't generate alerts

services/github_service.py
This is unnecessary and breaches PII when used in a CICD pipeline. We should let the caller of this method decide what to log.
=> :recycle: Remove logging statement

bin/identify_dormant_github_users.py, test/test_bin/test_identify_dormant_github_users.py
When the dormant user count exceeds ten users, the slack message becomes extremely difficult to read.
Here is an example of the hard to read slack message:
https://mojdt.slack.com/archives/C033QBE511V/p1725378457120739
=> ♻️ Change the slack message to improve readability

bin/identify_dormant_github_users.py
The bots added in this commit have been identified as one we should
ignore. The commit also sorts the list alphabetically.
=> ✨ Add robot accounts to the ALLOWED_BOT_USERS constant

terraform/github/repositories/ministryofjustice/operations-engineering-flask-template.tf
The idea behind this is to allow the Operations Engineering team to quickly create applications based on a tried and trusted Flask template. All of our Flask applications (join/dns-form, etc) appear identical in several areas. By creating a boilerplate template, we should improve velocity and standardise best practices.
=> :sparkles: Add a Flask template repository to increase velocity

terraform/github/repositories/ministryofjustice/operations-engineering-cloud-platform-namespace.tf
The module will allow operations engineering the ability to quickly create a cloud platform namespace.
=> :sparkles: Add new repository to hold a cloud platform tf module

config/constants.py
😿 As he no longer works for the service.
=> :fire: Remove Steve's account

terraform/auth0/operations-engineering/clients.tf
This allows us to make auth0 calls from the dev dns form. It connects to https://github.com/ministryofjustice/operations-engineering/issues/4839
=> :sparkles: Add dns-form-dev auth0 client

terraform/github/repositories/ministryofjustice/github-actions.tf
This pull request updates the description of the GitHub Actions module in the `terraform/github/repositories/ministryofjustice/github-actions.tf` file to better reflect its purpose and usage.
* [`terraform/github/repositories/ministryofjustice/github-actions.tf`](diffhunk://#diff-edeb272f5377159c99fa3e1e05aa66b8da825b3a69061e7a296e335801ffd688L8-R8): Updated the description to "A collection of reusable GitHub Actions for the Ministry of Justice, designed to streamline and enhance workflows across our projects."
=> :recycle: Reword the description of github-actions

.github/workflows/job-generate-github-standards-report.yaml, services/github_service.py, test/test_services/test_github_service.py
- In relation to https://github.com/ministryofjustice/operations-engineering/issues/4962
- To fix `Generate GitHub Standards Report` job failing intermittently 
- Moved the Cron Schedule back 2 hours, we have a couple of other jobs that run at 4:00am that also use the same token - with this one being a heavier process so will generally be the one hitting the limit
- Fixed an error with the retry logic where were catching `TransportQueryError` - this is used when there is an issue with the query i.e. syntax. We now catch `TransportServerError` which was the exception being raised in the case of the failing workflow. The response status was 403, which lines up as to what we expect with a rate limiting issue.
---
=> 🔧 Fix `Generate GitHub Standards Report` Workflow Failing

.github/workflows/experiment-identify-github-audit-log-dormant-users.yml, .github/workflows/experiment-identify-non-committers.yml, test/test_bin/test_archive_repos.py, test/test_bin/test_remove_stale_outside_collaborators.py
We are getting false positives on import order linting. This is due to a [known issue](https://github.com/pylint-dev/pylint/issues/3222) with isort.
Also pinned some action versions that were failing our check.
- Ignores added for C0411 on relevant files.
- Pinned failing action versions.
No notes!
---
=> :no_entry_sign: Ignore Import Order False Positives

services/operations_engineering_reports.py
- To fix the standards report failing by reducing batch size on post requests ([example failure](https://github.com/ministryofjustice/operations-engineering/actions/runs/11905041025/job/33174847257))
- Reduced the batch size from 100 to 10
- From looking at the server logs on the reports app, DynamoDB starts to slow down it's response, with the slowest responses being around 3 seconds. With a batch size of 100, you would need a timeout of ~300 seconds to handle a rate-limited batch. Reducing the batch size to 10 means a request can be handled with a timeout of ~30 seconds. The reports app is currently set to 120 seconds before a timeout, which explains why a batch size of 100 fails when DynamoDB starts to rate-limit requests. A batch size of 10 should be small enough to ensure requests …
=> 🔧 Fix Standards Reports Failing by Reducing Batch Size

.github/workflows/job-identify-dormant-github-users-v2.yml, bin/identify_dormant_github_users_v2.py, services/github_service.py, test/test_bin/test_identify_dormant_github_users.py, test/test_utils/test_environment.py
• To try to reduce the frequency of hitting the rate limiting by using a separate token per org. And to take this opportunity to ensure the tokens used adhere to POLP.
• ♻️ GH_ADMIN_TOKEN replaced with one token per org & tokens added to repo secrets
• 🧪 Updated corresponding tests
• ✨ These tokens are new FG-PATs with read only minimum privileges
• ♻️ Updated some print statements to `logging.info` and added `logging.info` to track requests 
• Multiple tokens do nothing for rate limiting - the rate limiting is per repo; POLPyness is improved though.
---
=> Replace single token with one per org

bin/fetch_github_actions_quota.py, services/github_service.py, test/test_bin/test_fetch_github_actions_quota.py, test/test_services/test_github_service.py
GitHub changed the way how the gha minutes quota can be retrieved for the enterprise. In the past the gha quota had to be retrieved per organization. Current Github API version allows to request Usage report, which gives usage data broken down by repository. 
Functional Requirements (What):
•[#5182](https://github.com/ministryofjustice/operations-engineering/issues/5182)
---
=> Gha quota update

.github/workflows/job-identify-dormant-github-users-v2.yml, .github/workflows/job-identify-dormant-outside-collaborators.yml, bin/identify_dormant_outside_collaborators.py, services/github_service.py, services/slack_service.py, test/test_bin/test_identify_dormant_outside_collaborators.py, test/test_services/test_github_service.py, test/test_services/test_slack_service.py
• To be able to track dormant Outside Collaborators in both MoJ GH Orgs and identify those who have made no commits to any repo they are affiliated with since the given datetime.
• ✨ Identify dormant outside collaborators identifies OCs who have made no commits to any repo they are affiliated with
• ♻️ Removed experimental ref in Identify Dormant GitHub users
• ✨ New Slack message re Dormant OCs and tests
• ♻️ Rejig GQL collaborators code to return repo visibility info as well
• ✨ 🧪 New tests
• We are most concerned with recovering GH licences and as a back stop for ex-OCs; this new workflow defines dormant OCs as those who have made no commits to any repo they are affiliated with since the given datetime. People with read only access are therefore considered dormant.
---
=> Identify dormant outside collaborators
