ministryofjustice/operations-engineering

- source/index.html.md.erb
Publish first iteration of home page and added link for Github external collaborators
> Publish home page

- source/index.html.md.erb
Includes publishing first homepage content.
> Merge ad-content branch to main

- source/documentation/runbooks.html.md.erb
- source/documentation/runbooks/os-places-api-key-management.html.md.erb
Creating OS Places runbook and links to runbook from menu.
> Creating OS Places Runbook

- source/documentation/runbooks.html.md.erb
- source/documentation/runbooks/manual-ssl-certificate-processes.html.md.erb
> Add Gandi ssl certs runbook

- source/documentation/services.html.md.erb
Add link to SSL Certificate guidance
> Add link to SSL Certificate guidance

- source/documentation/runbooks.html.md.erb
> Add link "collabs via fork" runbook

- source/documentation/services/os-places.html.md.erb
Create OS Places User Guidance
> Create OS Places User Guidance

- source/documentation/services.html.md.erb
Add link to OS Places User Guidance
> Add link to OS Places User Guidance

- source/documentation/services/domain-management.html.md.erb
Create Domain Management guide
> Create Domain Management guide

- source/documentation/services.html.md.erb
Link to new Domain Management guide
> Update services with Domain Management

- README.md
This PR removes `master` and changes it to `main` in the README.
> Change `master` to `main`

- source/documentation/services/sentry.html.md.erb
> Reviewed Sentry guidance

- source/index.html.md.erb
Reverts ministryofjustice/operations-engineering#129
> Revert "Update review date"

- source/documentation/alliance/alliance.html.md.erb
This is the new page to publish our Team Alliance
> Add Team Alliance

- source/documentation/services/sentry.html.md.erb
> Issue 148: Updates Sentry documentation to include information about performance tracing

- README.md
- config/tech-docs.yml
~~updates the header link to point to an existing page~~ The link needs to remain as is for it work in GH pages
> Fix links and readme

- source/documentation/runbooks/ops-eng-communications-plan.html.md.erb
This is a page that set out how, when, and where we communicate with our users and stakeholders
> Create Communications Plan runbook

- source/index.html.md.erb
> Add direct link to the Slack channel

- .github/ISSUE_TEMPLATE/operations-engineering-story.md
Standard template to use for creation of user stories/issues
> Create Operations Engineering Story Template

- source/documentation/services/os-places.html.md.erb
Changes in cost information to reflect PSGA.
> Update costs information

- .github/ISSUE_TEMPLATE/support_request.md
Add a new Issue Template for support requests
> Support request template

- source/documentation/alliance/alliance.html.md.erb
Update team alliance following retrospective discussion
> Update team alliance

- source/documentation/runbooks/new-joiners.html.md.erb
Adds details of slack channels that new team members need to be added to after joining
> Add slack channels

- source/documentation/services.html.md.erb
To help people who are unfamiliar with it
> Expand MTA-STS acronym

- scripts/python/archive-allow-list.txt
> Add analytics-platform-auth0 to archive allow-list

- source/documentation/services/dockerhub.html.md.erb
Adds additional instructions to users to add a name an ID based on their actual name.
> Add sentence about creating new IDs

- source/documentation/runbooks/dns/manual-ssl-certificate-processes.html.md.erb
> ✨Add link to `swim-lane diagram` for `renewing expiring SSL certificates`

- scripts/python/amend-user-repository-access.py
These changes aren't necessarily correct but thought it was best to visualise the logical differences between the scripts prior to my refactors.
I've ignored the following differences:
- Print statements
- Timeouts
- Comments (mainly)
- References to `ministryofjustice` vs `moj-analytical-services`
- `badly named repo` variable
> 🍻 Merge logical differences between scripts prior to adding Rate Limiter

- .github/workflows/auto-review.yml
- .github/workflows/move-dependabot-issues.yml
- .github/workflows/support-tickets.yml
- .github/workflows/unit-tests.yml
This PR contains a few changes that are worth noting and a few others that are purely aesthetic.
- Title changes 🤭 
- Only run the auto reviewer on `source/` directory changes
- Run the support changes sequentially following the guide: https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow#example-not-requiring-successful-dependent-jobs
> Various GitHub Action Changes

- source/documentation/adrs.html.md.erb
- source/documentation/adrs/adr-002.html.md.erb
- source/documentation/adrs/adr-008.html.md.erb
Multiple changes:
- Adds new ADR (008)
- Updates existing ADR (002)
- Updates ADR index page
> Update Sentry Spike Protection ADR

- source/documentation/runbooks/internal/new-joiners.html.md.erb
Replaces LastPass section. Also removes old Google Groups.
> Update for 1Password access

- .github/workflows/mojas-archive-repos.yml
- python/mojas/archive_repositories.py
- python/mojas/config/archive-allow-list.txt
- python/mojas/lib/MojArchive.py
- python/mojas/lib/MojGithub.py
A lift and shift phase to help quickly archive the operations-engineering repository.
There are SonarCloud issues, but these will be addressed later when the code is refactored.
> 🚡 Lift and shift the `archive_repositories` script from `moj-analytical-services`

- python/services/github_service.py
> 🔧 Fix `add_all_users_to_team` script by passing the object instead of string

- source/documentation/adrs/adr-003.html.md.erb
Reviewed ADR-003 with Nick, no changes required.
> Update ADR-003 review date

- python/test/test_github_service.py
This commit tests two cases in which data might not be returned to the fetch_all_repositories_in_org method.
> :white_check_mark: Add missing tests for fetching all repositories

- .github/ISSUE_TEMPLATE/operations-engineering-story.md
This template will be used to record user stories from stakeholders, capturing their functional and non-functional requirements, acceptance criteria, and any additional notes.
> 📝 Change user story template with new format

- .github/workflows/remove-locked-repo-collaborators.yaml
- python/scripts/remove-collaborator-locked-repos.py
This script was removed here https://github.com/ministryofjustice/github-collaborators/commit/1c1aa876ea48e72e1dfcf39807eb111930434339
This initial commit is only a copy and paste job - future PRs will refactor the code to align with this repos standards
> 🍻 Migrate `remove-locked-repo-collabators.py` from `github-collaborators` repository

- .github/ISSUE_TEMPLATE/github-feature-requests.md
This PR connects to https://github.com/ministryofjustice/operations-engineering/issues/3147. When developers create a new issue using this template, they'll see this pre-populated content, which they can fill out with their specific request. The template ensures all feature requests are consistently formatted, making them easier to process and manage.
> 📝  Add GitHub feature request template

- source/documentation/runbooks/internal/issue-labels.html.md.erb
This PR adds:
1) New Workflow Status - Unplanned (e.g. responding to Sentry Alerts) 
2) New Type of Story - Development (e.g. writing some code) 
3) New Language Types - Ruby, Python and Terraform (to identify language that will be used to complete a story)
> Add new Labels

- python/config/inactive-users.toml
- python/requirements.txt
- python/scripts/report_on_inactive_users.py
- python/services/github_service.py
- python/services/slack_service.py
- python/test/test_github_service.py
- python/test/test_report_on_inactive_users.py
- python/test/test_slack_service.py
This PR connects to https://github.com/ministryofjustice/operations-engineering/issues/3149 and introduces a new beta feature to monitor user activity within a GitHub team. Utilising configuration in a TOML file, the system will identify users who haven't committed any code in the past 18 months, notify a specified Slack channel, and optionally remove them from the corresponding GitHub team.
- **Inactivity Monitoring**: Checks user activity within the specified GitHub organisation and identifies inactive users based on the given threshold (18 months).
- **Slack Notifications**: Sends alerts to the configured Slack channel (`#operations-engineering-alerts` in the example below) regarding inactivity.
- **Team Removal**: Optionally removes the identified inactive users from the …
> ✨ Self managed GitHub Teams Beta

- source/documentation/runbooks.html.md.erb
- source/documentation/runbooks/services/public-github-repositories.html.md.erb
- source/documentation/runbooks/services/storing-code-in-public.html.md.erb
- source/documentation/services/moj-github.html.md.erb
This PR connects to https://github.com/ministryofjustice/operations-engineering/issues/3153 and relates to an item gathered during user research. Developers are unsure what should and should not be allowed in a public repository. The documentation in this PR addresses this in the form of a style guide. Using a do's and don'ts format, we can easily collate all the amazing information in the public on what and how to treat public repositories.
> 📝 Add a do's and don'ts guide for using public repositories

- python/scripts/archive_repositories.py
This PR adds the following repo to the MoJ allow list to prevent archiving:
- oracle-policy-automation-docker
> Adds a repo to the allow list

- python/scripts/archive_repositories.py
Adds criminal-forecasting-rap repo to the allow list to prevent archiving
> Adds a repo to allow list

- .github/workflows/tests.yml
- requirements.txt
- services/slack_service.py
- test/test_slack_service.py
- Reduce the risk of breaking changes being introduced by fixing Python dependency versions
- Fixed Python dependency versions
- Put requirements.txt in alphabetical order so it's easier to find dependencies
- Added `pip-review` as a dependency to easily update versions in the virtual environment
- Highlight development dependencies vs production dependencies (ideally we split these into separate files)
- Fixed a link in the Slack alert
> ✨ Add fixed versions to python dependencies 🔧 Fix link to runbook

- .github/workflows/check-for-low-github-seats.yaml
- bin/alert_on_low_github_licences.py
- test/test_low_github_licences.py
This commit connects to https://github.com/ministryofjustice/operations-engineering/issues/3764
> :sparkles: Add new Action to check for low licence threshold

- README.md
- To aid standardisation by explicitly documenting it, enabling it to be critiqued and updated in future
- Added a section to our readme to document our naming standards for workflow files
> ✨ Add our naming standards for workflow files to the `README.md`

- .github/workflows/cicd-terraform-github-repos.yml
- terraform/github/repositories/import_repositories.sh
- terraform/github/repositories/operations-engineering-devcontainer.tf
- Add operations-engineering-devcontainer repository into terraform management
> Import operations-engineering-devcontainer repository into terraform managment

- terraform/github/repositories/acronyms.tf
- terraform/github/repositories/cloud-platform-maintenance-pages.tf
- terraform/github/repositories/github-actions.tf
- terraform/github/repositories/github-collaborators.tf
- terraform/github/repositories/github.tf
- terraform/github/repositories/moj-terraform-aws-sso.tf
- terraform/github/repositories/moj-terraform-scim-github.tf
- terraform/github/repositories/operations-engineering-certificate-renewal.tf
- terraform/github/repositories/operations-engineering-devcontainer.tf
- terraform/github/repositories/operations-engineering-documentation-browser-extension.tf
- terraform/github/repositories/operations-engineering-example.tf
- terraform/github/repositories/operations-engineering-join-github.tf
- terraform/github/repositories/operations-engineering-metadata-poc.tf
- terraform/github/repositories/operations-engineering-reports.tf
- terraform/github/repositories/operations-engineering-runbooks.tf
- terraform/github/repositories/operations-engineering-user-guide.tf
- terraform/github/repositories/operations-engineering.tf
- terraform/github/repositories/tech-docs-github-pages-publisher.tf
- terraform/github/repositories/tech-docs-monitor.tf
- terraform/github/repositories/technical-guidance.tf
- terraform/github/repositories/template-documentation-site.tf
- terraform/github/repositories/template-repository.tf
- terraform/github/repositories/terraform-aws-mtasts.tf
- terraform/github/repositories/terraform-github-repository.tf
- terraform/github/repositories/terraform-template-poc.tf
- Update github repo module source to https://registry.terraform.io/modules/ministryofjustice/repository/github/latest
- Remove redundant tags attribute
> Update source and remove tags attribute

- .github/workflows/cicd-terraform-github-repos.yml
- .gitignore
- .pre-commit-config.yaml
- Makefile
- README.md
- terraform/github/repositories/test-repo-levg.tf
- Make target to setup pre-commit
- Pre commit config 
- README changes
- Removal of redundant steps from TF pipeline
> Setup terraform pre commit hooks

- hosted_zones.json
- requirements.txt
- test/test_bin/test_export_route_53.py
- test/test_services/test_route_53_service.py
- test/test_services/test_s3_service.py
- Unit tests for:
Route53 service
save_r53_backup_file function in S3 service
export route 53 in bin 
- Uses moto package to mock boto3 client
> R53 backup unit tests

- .github/workflows/job-route-53-backup.yml
- services/route_53_service.py
- test/test_services/test_route_53_service.py
- Structure of JSON backup amended to {zone_id: {zone_name: value, records: [...]}}, to store name of each hosted zone.
- Unit-test updates.
> Change json structure and unit test updates

- .github/workflows/cicd-trivy-dependency-scan.yml
> ✨ Added Trivy Vulnerability Scan Action

- .github/workflows/cicd-mega-linter.yml
> ♻️ Modified action to lint the entire codebase on workflow_dispatch

- .github/dependabot.yml
- .github/workflows/cicd-mega-linter.yml
- .github/workflows/job-alarm-for-stale-pull-requests.yml
- services/github_service.py
- services/route_53_service.py
- test/test_services/test_github_service.py
- test/test_services/test_route_53_service.py
- test/test_services/test_slack_service.py
- test/test_services/test_standards_service.py
To bring our operations engineering repo in line with Megalinter standards
- Python formatting
No notes to speak of.
> Megalinter Fixes Round 1

- .github/pull_request_template.md
- Ensures standardisation on our pull requests (which we are doing anyway).
- Ensures we update dependencies when working on them.
- A pull request template that we can use to remind us to test and update deps.
-
> :sparkles: Add a pull request template to ensure standardisation

- requirements.txt
Updated the Version from aiohttp 3.9.1 to 3.9.2 & cryptography 41.0.7 to 42.0.4
>  Bump the version from aiohttp 3.9.1 to 3.9.2 & cryptography 41.0.7  to 42.0.4

- .pylintrc
- services/github_service.py
- services/metadata_service.py
- services/operations_engineering_reports.py
- services/route_53_service.py
- services/s3_service.py
- services/slack_service.py
- test/test_bin/test_backup_route_53.py
- test/test_bin/test_dormant_users.py
- test/test_bin/test_sentry_usage_alert.py
- test/test_services/test_auth0_service.py
- test/test_services/test_github_service.py
Discussion around proposed changes to operations engineering repository.
Please see commit history for full changes.
No notes.
---
> Proposed Pylint Changes to Operations Engineering Repository

- .pylintrc
- test/test_services/test_github_service.py
- test/test_services/test_notify_service.py
- test/test_services/test_route_53_service.py
- test/test_services/test_s3_service.py
- test/test_services/test_slack_service.py
- test/test_services/test_standards_service.py
Fixes all pylint errors in the repo (a lot through ignoring in specific contexts)
Please check commit history for changes.
There seemed to be an issue when ignoring specific errors through a comment in the test_github_service.py file, so I've ignored them globally for now as they only appear in the test context.
---
> Final Megalinter Pylint Fixes for Operations Engineering

- bin/alert_on_low_github_actions_quota.py
- services/github_service.py
- test/test_bin/test_alert_on_low_github_actions_quota.py
- test/test_services/test_github_service.py
naming of gha minutes quota check function
> naming of gha minutes quota check function

- .github/workflows/cicd-trivy-dependency-scan.yml
- .github/workflows/job-alarm-for-stale-pull-requests.yml
- .github/workflows/job-alarm-unowned-repository.yaml
- bin/alert_on_low_github_actions_quota.py
- services/github_service.py
- test/test_bin/test_alert_on_low_github_actions_quota.py
- test/test_services/test_github_service.py
- test/test_services/test_sentry_service.py
Another PR to bring our operations-engineering repo in line with Megalinter suggestions.
Please check commit history for detailed changes.
No notes.
---
> General Megalinter Fixes

- bin/dormant_users.py
• Removed users from the allow list. There is no reason why users should be added to this allow list. It should be reserved for bot accounts.
• Removed users from the allow list.
> Update dormant users allow lists

- bin/alert_on_low_github_actions_quota.py
- services/github_service.py
- test/test_bin/test_alert_on_low_github_actions_quota.py
- Also log total minutes used for info.
> Link runbook in Slack notification for low gha minutes

- .github/workflows/job-support-stats-reporting.yml
• This PR is the initial setup for reporting support stats into the Operations Engineering channel on a daily basis.
• Added a new workflow file - /.githuhb/workflows/job-support-stats-reporting.yml
Added a new file to be used for the script(currently empty) - /bin/support_stats_reporting.py
•
---
> Adds support stats workflow

- .github/workflows/job-alarm-for-low-gandi-funds.yml
Basic GitHub Action setup added for testing the script in progress on a separate branch.
The two required files have been added so the script can be tested separately on another branch before it's ready to be merged into main.
•
---
> Basic Setup for Gandi Funding Alerts

- .github/workflows/job-identify-dormant-github-users.yml
- bin/identify_dormant_github_users.py
- Config for auth0 and github services
- auth0 active users list
- list comparison to identify dormant users
> Auth0 stuff

- .github/workflows/test-get-audit-log-users.yml
•
• 
This workflow will be removed once testing is complete.
---
> :sparkles: Created temporary workflow to trigger script

- bin/identify_dormant_github_users.py
- test/test_bin/test_identify_dormant_github_users.py
- Grab usernames from auth0 log output.
- And unit tests for functions.
> auth0 log output and unit tests

- bin/identify_dormant_github_users.py
- test/test_bin/test_identify_dormant_github_users.py
Auth0 active users component of dormant users Python job
- setup_environment function grabs auth0 credentials passed in as arguments from cli
- get_audit_logs function checks active auth0 users
- identify_dormant_users function checks all users against active users
- Main function identify_dormant_github_users wraps aforementioned functions
> Auth0 active users component of dormant users Python job

- config/constants.py
• This PR adds Vijay to the list of team members. Noticed that in the weekly GitHub added user stats that Vijay is incorrectly identified as "external".
• Vijay added to team member constants.
> Add Vijay to list of Ops Eng Team Members

- .pre-commit-config.yaml
- bin/alert_on_low_github_actions_quota.py
- Adds automatic Python formatters to adhere to flake8 standards.
- Reference: https://github.com/PyCQA/flake8/blob/main/.pre-commit-config.yaml
> Flake8 Python formatter pre commit hook

- services/github_service.py
- To make debugging easier when issues occur during archiving a repository
- Changed skipped repos into debug logs since these are typically not cause for concern
- Added a line to show the name of a repository before it is about to be archived. To allow for easy identification of a repository that can't be archived
---
> ♻️ Refactor logging in archive repositories process

- services/github_service.py
- test/test_services/test_github_service.py
- To add an additional check to the archive repo process so newly created repositories exit early
- Added a new check to exit early when a repository has been created within the cutoff period
- The additional check saves the call to GitHub to get the commit history when a project has been created within the cutoff date. Also reduces the noise on the number of repositories to "manually check"
---
> ✨ Add repo creation date check to archive repo process

- .github/workflows/job-generate-pat-token-report.yml
To enable the ability to run the PAT token code on a branch for testing purposes.
New GitHub workflow added with the ability to run on dispatch.
•
---
> :sparkles: Added main workflow to enable testing on pat token branch

- .github/workflows/job-generate-pat-token-report.yml
- bin/generate_pat_token_report.py
- services/github_service.py
- test/test_bin/test_generate_pat_token_report.py
- test/test_services/test_github_service.py
This adds an alert to the operations-engineering-alerts channel if org-level PATs have found to have expired.
- New workflow created to run every Friday at 8am.
- Script created to check for expired org-level PAT(s)
- New [GitHub App](https://github.com/organizations/ministryofjustice/settings/installations/49899947) created to handle the api interactions
•
---
> GitHub Expired PAT Alerting

- bin/archive_repositories.py
Adds a repo to the archive allow list
Updated archive-repositories.py analytical services allow list to prevent "segmentation-data-creation" repo from being auto archived.
•
---
> Adds repo to archive allow list

- bin/archive_repositories.py
Updates the auto archive allowed repo list
Amends archive-repositories.py auto archive allow list with ministryofjustice/staff-infrastructure-print-xwc
•
---
> Updates allow list

- terraform/github/repositories/ministryofjustice/operations-engineering-kpi-dashboard-poc.tf
- To add a new repository
- Added `operations-engineering-kpi-dashboard-poc` repository
- NA
---
> ✨ Add `operations-engineering-kpi-dashboard-poc` repository

- bin/dormant_users.py
• Adds `analytical-platform-bot` account to allow list to avoid removal for account from MoJ GitHub Org.
•  `analytical-platform-bot` added to MoJ Org allow list
> Add analytical-platform-bot user to allow list

- bin/identify_dormant_github_users.py
- test/test_bin/test_identify_dormant_github_users.py
- test/test_utils/test_environment.py
- utils/environment.py
• This pull request aims to standardise the way environment variables are accessed and managed across the repository. Currently, numerous disparate methods for retrieving secrets from environment variables exist, leading to inconsistency and potential errors. Introducing a unified approach should enhance code maintainability, readability, and reliability.
• Added a new utility module `environment.py` which includes the `EnvironmentVariables` class. This class is designed to dynamically retrieve and validate environment variables.
• The `EnvironmentVariables` class initialises environment variables based on a provided list and raises an error if any required variables are missing. This approach standardizes the pattern for environment variable access.
• Implemented comprehensive unit tests …
> ✨ Add Utils Directory and Standardise Environment Variable Pattern

- bin/support_stats_reporting.py
• This PR has been raised to fix a 'KeyError' introduced by the previous commit.
• Dictionary had stopped working and was generating a 'KeyError'.  To fix this I added a new import called 'collections'
which enables the use of a default dictionary (defaultdict)
•
---
> Replace dictionary with default dictionary module

- bin/identify_dormant_github_users.py
I'm not sure why the ide didn't complete this task, but this commit should make it a little more readable on screen.
> 💅 Format docstring to improve readability

- .github/workflows/cicd-trivy-dependency-scan.yml
To pick up on the appropriate severity level (HIGH) of vulnerabilities when Trivy scans the repository.
Severity level has changed from CRITICAL to HIGH.
No notes.
---
> :recycle: Modified scan level in workflow from CRITICAL to HIGH to pick up agreed vulnerabilities.

- data/support_stats/support_stats.csv
Daily sr stats update, data for 170524
•Upload daily stats for 17/05/24
• The support_stats.csv file has been updated with support request data from 17/05/24
•
---
> Update support_stats for 170524

- data/support_stats/support_stats.csv
• Updates the support stats data
• This PR updates the support stats data (support_stats.csv) with requests received from Fri 17th May to Thurs 23rd May.    
•
---
> Support stats update

- .github/ISSUE_TEMPLATE/dns-request.md
- .github/workflows/experiment-alert-on-new-dns-request.yml
To experiment with a new way of organising DNS record request information from users through a GitHub issue form template.
- New issue template created
- New GitHub Action created to trigger on the creation of relevant issues.
The idea here is to link users to the relevant issue via a runbook/Slack message, which will then raise the appropriate issue on the operations engineering board.
---
> New DNS Record Request Issue Template

- .github/ISSUE_TEMPLATE/dns-request.md
To convert the newly created template into a form.
Default issue template heading syntax removed.
•
---
> ♻️ Removed default issue template headings to enable form functionality

- .github/ISSUE_TEMPLATE/dns-request.yml
Forms are required to be .yml files.
.md -> .yml
•
---
> ♻️ Corrected Issue Form File Type

- terraform/github/repositories/ministryofjustice/operations-engineering-dns-form.tf
After adding this repository we can start creating our DNS form. This form will capture DNS change information that will be used downstream to manage our DNS estate. This commit follows the standard format required for a vanilla repository.
> :sparkles: Add new repository for DNS form capture

- config/constants.py
• PR adds `moj-operations-engineering-bot` to list of Ops Eng users
• Add `moj-operations-engineering-bot` to constants
> Add `moj-operations-engineering-bot` to list of Ops Eng users

- .github/workflows/cicd-mega-linter.yml
- .mega-linter.yml
This should improve startup time and help close the feedback loop. Currently, it takes approximately 3 minutes.
> :green_heart: Replace megalinter with a slim version

- bin/alert_on_unused_contexts.py
- services/circleci_service.py
- test/test_bin/test_alert_on_unused_contexts.py
- test/test_services/test_circleci_service.py
Small fix in main script and CircleCI service to remove unnecessary passing of a service instance between methods. This was left over after a small refactor.
Code and tests updated.
•
---
> CircleCI Context Check Fix

- .github/ISSUE_TEMPLATE/decomission_request.md
- .github/ISSUE_TEMPLATE/firebreak-template.md
- .github/ISSUE_TEMPLATE/github-feature-requests.md
- .github/ISSUE_TEMPLATE/maintenance_request.md
- .github/ISSUE_TEMPLATE/operations-engineering-story.md
- .github/ISSUE_TEMPLATE/trivy-vulnerability-template.md
Edit User Story template to clarify sections
> Update issue templates

- data/support_stats/support_stats.csv
• Updates support stat data
• support_stats.csv is now up to date with data for June (7th - 25th June 2024)
•
---
> Support data 030624

- bin/mass_permission_update.py
- test/test_bin/test_mass_permission_update.py
To keep our codebase healthy and relevant, we aim to refactor some of the older scripts within the operations_engineering repository each sprint. This time, it was the `mass_permission_update` script.
- Functionality has been moved out of main into separate methods.
- Test coverage added for the script.
No notes.
---
> ♻️ Refactor mass_permission_update Script

- .github/workflows/job-generate-pat-token-report.yml
🥫 
- Added `workflow_dispatch` option to action
- Updated to use commit hashed on third party actions.
No notes.
---
> :recycle: Enabled Running of PAT Check Action Manually for Debugging

- .github/workflows/job-remove-stale-outside-collaborators.yml
• To enable the remove stale collaborators workflow to operate on the `moj-analytical-services` organisation as well as the `ministryofjustice` organisation.
• ✨ Add an extra step to run the remove stale collaborators script on the  `moj-analytical-services` organisation.
•
---
> Add step to remove MoJ Analytical Services stale outside collaborators

- data/support_stats/support_stats.csv
Re-uploading the full support_stats.csv file after fixing a merge conflict from another commit.
• This PR is to re-upload the full support_stats.csv file 
• A merge conflict from a different commit put the support_stats.csv file in an out of date state.  This will re-upload that file to make sure the support data is up to date.
•
---
> Fix a merge conflict with stats data

- bin/support_stats_reporting.py
• Adds support_stats_reporting.py back into the repo
• The support_stats.py was deleted whilst trying to resolve a conflict, repo was recloned before adding it back..  This adds the support_stats_reporting script back in, allowing reporting of support stats to slack to work again.
•
---
> Re-add the support script

- data/support_stats/support_stats.csv
Adds support stats data for 03/07/24
• Adds the latest support stats data
• support_stats.csv has been updated with data for 3rd June 2024
•
---
> Upload support stats data

- .github/workflows/cicd-terraform-dsd-iam.yml
- .github/workflows/cicd-terraform-github-repos.yml
- .github/workflows/experiment-get-usernames-from-github-slack-poc.yml
- .github/workflows/job-add-github-members-to-root-team-moj.yml
- .github/workflows/job-add-github-members-to-root-team-mojas.yml
- .github/workflows/job-alarm-for-unused-contexts.yml
- .github/workflows/job-alarm-unowned-repository.yaml
- .github/workflows/job-apply-standards.yml
- .github/workflows/job-archive-inactive-repos-moj.yml
- .github/workflows/job-archive-inactive-repos-mojas.yml
- .github/workflows/job-dormant-users-debug-mode.yml
- .github/workflows/job-dormant-users-first-email.yml
- .github/workflows/job-dormant-users-reminder-email.yml
- .github/workflows/job-dormant-users-remove-users.yml
- .github/workflows/job-generate-github-standards-report.yaml
- .github/workflows/job-remove-stale-outside-collaborators.yml
• To restrict GH token permissions to what is necessary and have better visibility of token usage.
•  ♻️ Replaced bot token with well-named, expiry dated, reduced permissions Classic token for use only in this repository
• A couple of other Classic GH tokens used in this repo for the audit stuff.
---
> Replace refs to old classic token with new well-named token

- data/support_stats/support_stats.csv
• Upload support stats data for 9th July 2024
• support_stats.csv has been updated with support stat data for 9th July 2024
•
---
> Upload support stats for 09/07/24

- data/support_stats/support_stats.csv
• Adds support request data for 10/07/24
• support_stats.csv has been updated with data for 10/07/24
•
---
> Upload support data for 10/07/24

- .github/workflows/cicd-terraform-auth0.yml
This PR fixes the auth0 pipeline by bringing it up to the standard of our other terraform pipelines. It also introduces a terraform apply on push to main function and the ability to create a comment in a PR that contains the apply workflow link.
> :green_heart: Add terraform apply on push to main and format

- terraform/dsd/iam/operations_engineering_test_secrets_manager_role.tf
To enable access the resource-based policy attached to the secret.
- `"secretsmanager:GetResourcePolicy"` added to policy
•
---
> :recycle: Updated the permissions on the secrets_manager_policy

- .github/workflows/cicd-terraform-auth0.yml
This appears to have been a copy-and-paste error.
> :recycle: Correct workflow name

- terraform/dsd/iam/assume_cloud_platform_route53_read_role.tf
- Fixes https://github.com/ministryofjustice/operations-engineering/pull/4640 (potentially)
- [Example Error](https://github.com/ministryofjustice/operations-engineering/actions/runs/9894566563/job/27332380688#step:15:71)
- Added square brackets to the policy statement (as advised by some person on the interwebs and also aligns with how we do it in the dormant users file)
- Fixed the policy syntax to be HCL instead of JSON
- 🤞
---
> 🔧 Fix `MalformedPolicyDocument` by  Using HCL instead of JSON for Policy Syntax

- terraform/auth0/README.md
This commit closes https://github.com/ministryofjustice/operations-engineering/issues/4044
> :memo: Document the Auth0 Terraform configuration

- data/support_stats/support_stats.csv
• Adds support data for 11th July 2024
• support_stats.csv has been updated with support data from 11th July 2024
•
---
> Upload support data for 110724

- .github/workflows/cicd-terraform-github-repos.yml
- terraform/github/repositories/variables.tf
To enable to terraform plan to correctly obtain GitHub owner information.
- Added an environment variable to be picked up by Terraform.
•
---
> Added GitHub Owner Environment Variable

- data/support_stats/support_stats.csv
• Adds support stats data for 12/07/24
• support_stats.csv has been updated with support data for 12th July 2024
•
---
> Upload support stat data

- .github/workflows/cicd-terraform-github-repos.yml
To enable secrets to apply correctly to the organisation.
Specific export of GITHUB_OWNER environment variable from workflow.
•
---
> Exported GITHUB_OWNER Environment Variable

- data/support_stats/support_stats.csv
• Add support request data for 15/07/24
• support_stats.csv has been updated with support request data for 15th July 2024
•
---
> Upload support stat data for 15/07/24

- data/support_stats/support_stats.csv
• Adds support stats data for 16/07/24
• support_stats.csv has been updated with support request data from 16th July 2024
•
---
> Upload support stats data for 160724

- .github/workflows/experiment-fetch-secrets-from-aws.yml
- bin/fetch_secrets_from_aws.py
- services/pingdom_service.py
- services/secret_manager_service.py
To prove that we can access secrets stored in AWS Secrets Manager in code as an alternative to secret injection through Terraform.
- New Pingdom service added as an example use case for secret management.
- New Secret Manager service added to retrieve secrets from AWS
- Workflow and script included to trigger logic.
•
---
> PoC: Accessing AWS Secrets in Code with Boto3

- .github/workflows/experiment-fetch-secrets-from-aws.yml
- Pipfile
- Pipfile.lock
- bin/fetch_secrets_from_aws.py
- services/pingdom_service.py
- services/secret_manager_service.py
To make the retrieval of secrets as simple as possible, I've switched to a system that enabled secret caching on the client. Read more [here](https://docs.aws.amazon.com/secretsmanager/latest/userguide/retrieving-secrets_cache-python.html).
This will enable us to retrieve a set of secrets once to be used by the application, rather than making many calls to AWS Secrets Manager.
- Pingdom Service's URL parameters corrected.
- AWS Secret Manager Caching package included.
- AWS credential setup corrected in the GitHub Action.
- Unnecessary AWS credential setup removed from main script.
- Moved to new secret caching logic in `secret_manager_service.py`
•
---
> ♻️ Switched to Secret Caching

- data/support_stats/support_stats.csv
• Adds support request data for 17th July 2024
• support_stats.csv has been updated with support request data for 17th July 2024
•
---
> Upload support data for 170724

- data/support_stats/support_stats.csv
• adds support request data for 19/07/24 
• support_stats.csv has been updated with support request data for 19th July 2024
•
---
> Upload support data for 19/07/24

- data/support_stats/support_stats.csv
• adds support request data for 22/07/24
• support_stats.csv has been updated with support request data for 22nd July 2024
•
---
> Upload support data for 220724

- data/support_stats/support_stats.csv
• adds support request data for 23/07/24 
• support_stats.csv has been updated with support request data for 23rd July 2024
•
---
> Upload support request data

- terraform/github/repositories/ministryofjustice/operations-engineering-find-a-github-repository-owner.tf
- In relation to https://github.com/ministryofjustice/operations-engineering/issues/4620
- To add a new repository to hold code for new experimental service
- Added a new repository called `operations-engineering-find-a-github-repository-owner`
- NA
---
> ✨ Add `operations-engineering-find-a-github-repository-owner` Repository

- terraform/github/repositories/ministryofjustice/acronyms.tf
• This PR removed the url from the repo description as no longer appropriate.
• Remove `homepage_url`
---
> Remove url from repo description

- data/support_stats/support_stats.csv
• add support request data for 31/07/24
• support_stats.csv updated with support request data for 31st July 2024
•
---
> Update support request stats data

- .github/workflows/cicd-terraform-auth0.yml
- .gitignore
- terraform/auth0/operations-engineering/clients.tf
• Set up KPI authentication
• ✨ Add auth0 resource for kpi dashboard
• wrt FIREBREAK: 🔥 Get KPI Dashboard Production Ready [#4612](https://github.com/ministryofjustice/operations-engineering/issues/4612)
---
> Set up KPI authentication

- terraform/auth0/operations-engineering/clients.tf
• Add terraform for MoJ Microsoft Authentication Dev auth0 app
•  ✨ Add terraform for MoJ Microsoft Authentication Dev auth0 app
•
---
> Add terraform for MoJ Microsoft Authentication Dev auth0 app

- terraform/auth0/operations-engineering-test/clients.tf
- terraform/auth0/operations-engineering/clients.tf
• Remove `encryption_key = {}`
• 🔥 Remove `encryption_key = {}` instances created by the auto terraform writer; these are OK on plan but not allowed for apply.
•
---
> remove encryption_key = {} - not allowed in apply

- terraform/auth0/operations-engineering/clients.tf
• ✨ Add Microsoft Authentication prod app
• ✨ Add Microsoft Authentication prod app
•
---
> Add Microsoft Auth0 prod app

- data/support_stats/support_stats.csv
• adds support request data for 13/08/24
• support_stats.csv has been updated with support request data for 13th Aug 2024
•
---
> Update support stats data

- terraform/auth0/operations-engineering/clients.tf
• 🧹 Tidying
•  🔥 Remove old `moj-auth0-azure-prod` Auth0 regular web app, no longer used (or shouldn't be 🤞 )
•
---
> delete old auth0 web app moj-auth0-azure-prod

- terraform/auth0/operations-engineering/clients.tf
• Rename apps to make the login screen more readable
•  remove the `Operations-Engineering` prefix from the name as this is superfluous, all our stuff is under the `operations-engineering` tenant, no need to labour the point.
•
---
> Rename Auth0 clients (apps) for readability

- data/support_stats/support_stats.csv
• adds support request data for 19/08/24
• support_stats.csv has been updated with support request data from 19th Aug 2024
•
---
> Upload support stats

- terraform/auth0/operations-engineering/clients.tf
• 🧹Keeping terraform tidy
• Remove the used moved blocks
•
---
> Remove used moved blocks

- services/github_service.py
- test/test_services/test_github_service.py
• The PR updates the hard-coded variables in the code to use parametric variables saved in the repository. 
• Added GHA_MINUTES_QUOTA_BASE_THRESHOLD and GHA_MINUTES_QUOTA_TOTAL_INCLUDED to repository variables.
• Updated the assignment logic for total_quota and base_alerting_threshold based on the new variables.
• Updated existing unit tests for GHA minutes and added new tests to cover the extraction of additional variables.
•
---
> updated hardcoded vars to parameters

- terraform/auth0/operations-engineering/clients.tf
• Updated URLs to match `dash` expectations.
• Callbacks updated to match those expected by `dash` OIDC implementation.
• Web origins updated to match those expected by `dash` OIDC implementation.
• Logouts removed as we don't have a logout page - though we should have something in here for best practise.
•
---
> Update KPI dashboard callbacks, logouts, web origins

- bin/configure_standards.py
- bin/sentry_usage_alert.py
- services/kpi_service.py
- test/test_bin/test_sentry_usage_alert.py
- test/test_services/test_kpi_service.py
- In relation to https://github.com/ministryofjustice/operations-engineering/issues/4761
- To track quota usage over time to spot trends and forecast future quota needs 
- Added Sentry Quota tracking for Errors, Transactions and Replays
- Still need to create the graphs to display this data
---
> ✨ Add Sentry Quota Usage Tracking

- .github/workflows/job-sentry-usage-alert.yml
- Fixes #4763 
- Added KPI Dashboard URL and API Key so the job can POST the quota to the API
- NA
---
> ✨ Add KPI Dashboard URL and API Key

- .github/workflows/job-fetch-github-actions-quota.yml
- bin/fetch_github_actions_quota.py
- services/kpi_service.py
•PR implements fetching of the daily gha quota usage for the enterprise.
• Added new script to bin/fetch_github_actions_quota.py
• Added tracking of github quota usage metric to kpi_service
• Added new workflow to trigger fetching every day at 00:00
• Consume and Display GHA Minutes over time #4754 
---
> Daily Fetching of GHA Quota

- terraform/github/repositories/ministryofjustice/operations-engineering-dns-form.tf
• Easily find the dev site
• 
•
---
> Add DNS Form URL to repo

- test/test_bin/test_fetch_github_actions_quota.py
- test/test_services/test_kpi_service.py
• PR includes unit tests for newly added gha quota fetching service 
• Added unit tests for bin/fetch_github_actions_quota
• Updated unit tests for services/kpi_service
• Consume and Display GHA Minutes over time #4754 
---
> Unit tests for gha fetching

- bin/archive_repositories.py
• Adds a repo to the allow list to prevent archiving
• archive_repositories.py has been updated. [laa-ccms-service-adapter](https://github.com/ministryofjustice/laa-ccms-service-adapter) has been added to the allow list preventing it from being archived.
•
---
> Add repo to allow list

- terraform/dsd/iam/dns_check_change_status.tf
- terraform/dsd/iam/github_oidc.tf
• To enable the DNS Check Change Status workflow and restrict it to only permissions required.
•  ✨ Added role for the Check Change Status DNS workflow to use
•
---
> Add role for the Check Change Status DNS workflow to use

- terraform/dsd/iam/dns_check_change_status.tf
• Enable check-change-status dns workflow to run GetChange 
• Added permission
•
---
> Add permission to get change

- terraform/auth0/operations-engineering/clients.tf
- In relation to https://github.com/ministryofjustice/operations-engineering/issues/4870
- To add an Auth0 Application that can be used by the Find a GitHub Repository Service
- Added an Auth0 Application that can be used by the Find a GitHub Repository
- Will need further work to actually integrate this into the application
---
> ✨ Add Auth0 App For Find a GitHub Repository Owner

- terraform/github/repositories/ministryofjustice/operations-engineering-certificate-form.tf
To create a new repository for [this](https://github.com/orgs/ministryofjustice/projects/52/views/4?pane=issue&itemId=81560165) firebreak task.
- New repository `operations-engineering-certificate-form` added using the operations engineering flask app template.
None for now.
---
> :sparkles: Added New Certificate Flask Application Repository

- bin/archive_repositories.py
• This PR adds `nixon-foi` to the archiver ignore list. The code isn't updated and is run infrequently.
• Update `archive_repository.py`
• [Request](https://mojdt.slack.com/archives/C01BUKJSZD4/p1727864785343309?thread_ts=1727711687.264599&cid=C01BUKJSZD4)
---
> Add `nixon-foi` to ignore list

- terraform/auth0/operations-engineering-test/connections.tf
The previous connection had the same name as the already existing connection that had been created manually in Auth0. This PR changes the name in order for a completely new resource to be created.
- Connection name changed to `Google Workspace Connection`
Once this has been created and confirmed to be working, we can manually delete the old connection from Auth0.
---
> :recycle: Renamed Google Connection Created in Terraform

- terraform/auth0/operations-engineering-test/connections.tf
> :recycle: Renamed Connection with Correct Formatting

- .github/ISSUE_TEMPLATE/operations-engineering-story.md
• Update User Story template
•  ✨ Add assumptions and risks sections
•
---
> Update User Story template

- .github/workflows/cicd-trivy-dependency-scan.yml
This solves this bug: https://github.com/ministryofjustice/operations-engineering/actions/runs/11557051458
> upgrade trivy scan action

- .github/workflows/exprimental-identify-dormant-github-users.yml
- .github/workflows/job-certificate-expire-test-run.yml
- bin/check_certificate_expiry.py
- services/gandi_service.py
- services/notify_service.py
- services/s3_service.py
• Migration of  Certificate Expiry Check code from https://github.com/ministryofjustice/operations-engineering-certificate-renewal/
• Job script certificate_expiry_check.py  moved to operations-engineering/bin 
• Services updated accordingly 
• Test run workflow added 
• All required secrets added to the repo. 
• Certificate Expiry Test Run https://github.com/ministryofjustice/operations-engineering/actions/runs/11630817758
---
> Certificates renewal migration

- bin/check_certificate_expiry.py
• Fix for  unsuccessful Certify Expiry Run 
• Added missing CERT_EXPIRY_TEMPALATE_ID to cert_config 
• Failed workflow run : 
https://github.com/ministryofjustice/operations-engineering/actions/runs/11763791889
---
> Bug Fix for unsuccesfull Cerfificate Expiry run

- .github/workflows/job-dormant-user-accuracy-report.yml
- bin/dormant_user_removal_accuracy_report.py
- services/github_service.py
- services/slack_service.py
- test/test_services/test_github_service.py
- test/test_services/test_slack_service.py
To notify the operations engineering team on the percentage of users that are rejoining after being removed.
- New GitHub workflow added to run through script functionality.
- New script added to gather audit log information on removed/rejoining users.
- Test coverage for new code.
•
---
> 🤖 Erroneous User Removal Report

- .github/ISSUE_TEMPLATE/decommission_request.md
- .github/ISSUE_TEMPLATE/maintenance_request.md
- .github/pull_request_template.md
- bin/check_for_new_github_owners.py
- bin/sentry_usage_alert.py
- services/pingdom_service.py
- services/slack_service.py
- terraform/auth0/README.md
- test/test_services/test_slack_service.py
To bring the operations-engineering repository back in-line with MegaLinter standards.
Please see the commit history for a detailed breakdown of linter issue fixes.
No notes.
---
> Megalinter Fixes

- services/github_service.py
- To ensure we have visibility of the failing workflow ([example](https://github.com/ministryofjustice/operations-engineering/actions/runs/11968818036/job/33368341037#step:6:15)) via a Slack Alert
- Refactored current default value logic to raise a ValueError when we receive a non 200 response from the API
- The workflow will still fail, I will raise another ticket to remedy the visible alert and update the relevant permissions on the token
---
> 🔧 Fix Workflow Not Failing When Bad Response From API

- .github/workflows/job-identify-dormant-github-users-v2.yml
- bin/identify_dormant_github_users_v2.py
- test/test_bin/test_identify_dormant_github_users.py
- Cron schedule to run on first of each month
- Slack integration
> Brush up dormant users v2

- .github/workflows/job-identify-dormant-github-users-v2.yml
- bin/identify_dormant_github_users_v2.py
- In relation to https://github.com/ministryofjustice/operations-engineering/issues/5127
- Set the default infrastructure to use MP instead of DSD
•
---
> ♻ Set MP Infrastructure as Default for Dormant Users Process

- .github/workflows/job-remove-stale-outside-collaborators.yml
• The PR removes remove Stale Collaborator from the AS Org. Code no longer required.
• Remove block relating to AS Org
---
> Remove AS Org Stale Collaborators code

- bin/identify_dormant_github_users_v2.py
- services/github_service.py
- test/test_services/test_github_service.py
- Ensure correct username case throughout get active committers logic.
> Debug get active committers

- .github/workflows/job-identify-dormant-github-users-v2.yml
- bin/identify_dormant_github_users_v2.py
- services/cloudtrail_service.py
- services/cloudwatch_service.py
- services/slack_service.py
- test/test_bin/test_identify_dormant_github_users.py
- test/test_services/test_cloudwatch_service.py
- test/test_services/test_slack_service.py
• To enable shorter cut off time to be selected when necessary
• Created an input selection DAYS_SINCE in the workflow when run manually and options.
• Updated code to use days_since variable, rather than hardcoded value of 90.
•
---
> Allow choice of 30, 60, 90 days, 90 default

- .github/workflows/job-alarm-for-github-actions-quota.yml
- .github/workflows/job-fetch-github-actions-quota.yml
• Updated names of secrets in workflow files for gh actions quota
> updated enterprise token secret name

- config/constants.py
• To get alerted sooner when seats are low
• 20 -> 50
•
---
> Increase GitHub license threashhold to 50 to trigger alert sooner

- dashboards/COAT 🧥-1742480956786.json
- dashboards/GPX PoC-1742480931514.json
- Add exports of our Grafana dashboards if we want to recreate in future.
> Add dashboard exports

- terraform/github/repositories/imports.tf
- terraform/github/repositories/ministryofjustice/github-actions.tf
- terraform/github/repositories/ministryofjustice/operations-engineering-certificate-renewal.tf
- terraform/github/repositories/ministryofjustice/operations-engineering-cloud-platform-namespace.tf
- terraform/github/repositories/ministryofjustice/operations-engineering-documentation-browser-extension.tf
- terraform/github/repositories/ministryofjustice/operations-engineering-find-a-github-repository-owner.tf
- terraform/github/repositories/ministryofjustice/operations-engineering-github-actions-dashboard.tf
- terraform/github/repositories/ministryofjustice/operations-engineering-kpi-dashboard.tf
- terraform/github/repositories/ministryofjustice/operations-engineering-runbooks.tf
- terraform/github/repositories/ministryofjustice/operations-engineering-support-metadata.tf
- terraform/github/repositories/ministryofjustice/operations-engineering-user-guide.tf
- terraform/github/repositories/ministryofjustice/operations-engineering.tf
- terraform/github/repositories/ministryofjustice/terraform-aws-mtasts.tf
- terraform/github/repositories/ministryofjustice/terraform-github-repository.tf
• To import the moj repos declared in TF into new state file
• importing 13 repos and associated team associations and branch protection
•
---
> Import moj tf repos

- .github/workflows/cicd-terraform-auth0.yml
- terraform/auth0/operations-engineering-test/imports-ops-eng-test.tf
- terraform/auth0/operations-engineering-test/main.tf
- terraform/auth0/operations-engineering-test/variables.tf
- terraform/auth0/operations-engineering/imports-ops-eng.tf
- terraform/auth0/operations-engineering/main.tf
Recommence management of auth0 resources in terraform.
• ✨ Point at new terraform bucket for auth0 state
• ♻️ Import existing auth0 resources into new state file for each auth0 tenant
•
---
> Point at new auth0 tfstate file & import existing

- .github/workflows/job-dormant-user-accuracy-report.yml
• It looks like we have two differently named repo secrets which must actually be alias for the same FG-PATs from the bot account. This PR standardises the naming.
• Standardised names of secrets used
• Manually delete the old secret from the repo secrets
---
> Standardise secret names

- terraform/github/repositories/ministryofjustice/operations-engineering.tf
• PR Updates link to new home of Ops ENg legacy guide
• Updates Repo URL
---
> Update repo Guide URL

- README.md
• This PR updates the link to the GitHub Standards Report
• Update link
---
> Update link to GitHub Standards Report

- terraform/github/repositories/ministryofjustice/coat-cur-data-pipeline.tf
• Add repo for CUR data pipeline using the desired template
• ✨ New COAT CUR repo
•
---
> Add new CUR repo with correct template

- .github/workflows/job-alarm-for-new-github-owners.yml
• This PR replace the GH Bot Audit Log secret with another secret that does the same thing. No use in having two secrets that do the same thing. This will allow us to remove an extra secret.
• Replace Audit Log Secret variable.
---
> Replace Audit Log Bot Token
